# Generated by Django 5.0 on 2023-12-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='news name')),
                ('full_text', models.TextField(verbose_name='article')),
                ('date', models.DateTimeField(verbose_name='date time')),
            ],
        ),
    ]
