# Generated by Django 5.0 on 2023-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Photo name'),
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=250, null=True, verbose_name='Slug fiels'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-created'], name='gallery_pho_created_90e0f2_idx'),
        ),
    ]
