# Generated by Django 5.0 on 2023-12-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='name')),
                ('story', models.TextField(verbose_name='story')),
                ('age', models.CharField(max_length=40, verbose_name='age')),
                ('image', models.ImageField(null=True, upload_to='post_images/')),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
        ),
    ]
