# Generated by Django 5.0 on 2023-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pers',
            options={'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
        migrations.AlterField(
            model_name='pers',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
